import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='es' className='dark:bg-slate-800'>
      <body className={inter.className}>
        <main className='container mx-auto max-w-2xl'>{children}</main>
      </body>
    </html>
  );
}
